### ISSUE TITLE
does dnscrypt-wrapper support client authentication?

### ISSUE THREAD

**Issue by oddboy** [cofyc/dnscrypt-wrapper#118]
Hi all,

I'm sniffing around dnscrypt and have a proof of concept (dnscrypt-proxy + dnscrypt-wrapper) working, but I'd love to add client authentication to it.  I see this mentioned in various places as a means of having a dnscrypt "server" be able to identify clients that are authorized to query it.  But I can't find much documentation about how this works or how to set it up.

is that something that dnscrypt-wrapper supports?  if so, is there any docs (or hints?) on how to generate an appropriate key to use on authorized clients?

Thanks!

Joel

**Comment by cofyc** [comment]
hi, dnscrypt-wrapper does not support client authentication now.

> I see this mentioned in various places as a means of having a dnscrypt "server" be able to identify clients that are authorized to query it.

I don't know much about this. Could you give me some information or links?

**Comment by jedisct1** [comment]
dnscrypt-proxy 1.x had the ability to use a fixed key pair, so servers can use the public key to identify clients.

Comodo, maybe Infoblox and some other big companies are using this to identify customers.

dnscrypt-proxy 2.x doesn't support this any more. If these companies need it, they can contribute code for a change instead of anonymous features requests and support requests.
