### ISSUE TITLE
Default expiration days is 1?

### ISSUE THREAD

**Issue by theodotos** [cofyc/dnscrypt-wrapper#156]
Hello,

I've been reading the documentation and got a bit confused. It says:

```
NOTE: By default, secret key expires in 1 day (24 hours) for safety. You can change it by adding --cert-file-expire-days=<your-expected-expiraiton-days>, but it's better to use short-term secret key and use key-rotation mechanism.
```

What's the reasoning behind that 1 day expiration? I'm guessing that it is not recommended to use the default value. Can you suggest an appropriate expiration time?

Also there is a minor typo in `<your-expected-expiraiton-days>` :)

**Comment by jedisct1** [comment]
This is the recommended expiration time, for two reasons:

1) Forward secrecy. If the secret key ever gets leaked, traffic more than 24 hours old cannot be decrypted any more, by anyone. Captured data is useless, the previous keys are gone forever.

2) Missing/broken key rotation mechanisms is the main cause of outages for all kinds of encrypted traffic. We initially saw virtually all DNSCrypt servers fail exactly a year after they had been set up. Because the key expired, there was no monitoring, nothing to renew them automatically.
With a 24 hours expiration, properly setting up automation becomes a no brainer. If it doesn't work, you will know the next day, not when you won't think about it any more. And if it works more than 24 hours, it will work forever :)

**Comment by theodotos** [comment]
I see :). So basically you need to come up with a reliable rotation mechanism and you are done.

Thanks @jedisct1
