### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by ebal** [Cofyc/dnscrypt-wrapper#41]
I am trying to install dnscrypt-wrapper but every 0.1.15 releases hits on this error:

git submodule update --init argparse
make: git: Command not found
make: *** [argparse/argparse.h] Error 127

but with git clone 
everything works fine.

Any idea for 0.1.15 releases ?
Thanks in advance

**Comment by Cofyc** [comment]
hi,




make: git: Command not found





this means make couldn't find git command to invoke.




But you can run git clone?




What does 'which -a git' show? You can reinstall git to system default bin path, such as /bin/git or /usr/local/bin/git. Or edit 'git' command in Makefile to its absolute path. (first find where you install git)




—
Yecheng Fu

**Comment by ebal** [comment]
All my test are on a clean/fresh centos7 docker image.
I am surely I am missing something ... 

here are all my tests: http://ebalaskas.gr/dnscrypt-wrapper.txt

1. first test: git clone (Submodule 'argparse' is there too)
2. dnscrypt-wrapper-v0.1.15.tar.bz2  (from github)
3. v0.1.15.tar.gz (from github)

# which git -a
/usr/bin/git

**Comment by Cofyc** [comment]
hi, ebal

1. do not download archive from https://github.com/Cofyc/dnscrypt-wrapper/archive/v<version>.tar.gz, because these files are archived from git source, and dnscrypt-wrapper have a submodule, which will not be archived.
2. you can git clone or download release archive: https://github.com/Cofyc/dnscrypt-wrapper/releases/download/v0.1.16/dnscrypt-wrapper-v0.1.16.tar.bz2, try v0.1.16 again?

**Comment by ebal** [comment]
Worked perfectly !
Thanks for your help.
